name: Build and Deploy to ECS

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/src/**'
      - 'frontend/public/**'
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push frontend image
        run: |
          FRONTEND_TAG=${{ secrets.ECR_REGISTRY }}/${{ secrets.FRONTEND_REPO }}:latest
          docker build -t $FRONTEND_TAG ./frontend
          docker push $FRONTEND_TAG


      - name: Build & push backend image
        run: |
          BACKEND_TAG=${{ secrets.ECR_REGISTRY }}/${{ secrets.BACKEND_REPO }}:latest
          docker build -t $BACKEND_TAG ./backend
          docker push $BACKEND_TAG


      - name: Update frontend ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.FRONTEND_SERVICE }} \
            --force-new-deployment

      - name: Update backend ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.BACKEND_SERVICE }} \
            --force-new-deployment
